# ./docker-compose.yml

version: '3'

services:
  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: ./php
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"